### ISSUE TITLE
Sync prioritisation MVP

### ISSUE THREAD

**Issue by aeplay** [garden-co/classic-jazz#396]
As empirically proven by @gu.dorsi's experimentation, syncing a big BinaryCoStream tends to stall concurrently syncing smaller CoValues. Having a system where sync messages are sent out according to different update priorities significantly helps alleviate this issue.

To keep it easy to provide different transport implementations for CoJSON Peers (websocket, storage peers, etc.) we want to limit their implementation to the "dumb" task of just sending messages.

The prioritisation should therefore happen in `cojson` itself, the suggested way to go about this is:

* Converting `PeerState` in `cojson/src/sync.ts` into a class that has the priority queue as internal state, dispatching from the priority queue into its `outgoing: OutgoingSyncQueue` 
  * the naming of the latter might need to be changed to distinguish the priority queue from the dumb queue of outgoing messages that we get from the peer definition
* The priority (numerical, 0 = lowest prio, ∞ = highest prio) is assigned to a whole CoValue on loading or creation, it generates `NewContentMessage`s with the according priority to be taken into account by the priority queue of each peer
  * Accounts & Groups have the highest default priority (3) because other CoValues depend on them for being readable
  * BinaryCoStreams have the lowest default priority (1) because they are most likely to have large chunks that might stall everything else
  * All other CoValues have priority (2)
* For now we just use the default priorities before we expose them for customisation to the user

**Comment by gdorsi** [comment]
## Update on the prioritization algorithm

Summarizing the requirements found so far:
- Needs to be low overhead as possible (is used by any peer, if it is slow it creates overhead in any communication)
- Should not fully block a given priority (means that low priorities should be processed even if there are higher priorities in the queue)
- The users should be able to assign custom priorities to co values
- The priority ranges are numerical (0 = lowest prio, ∞ = highest prio)

In [my current implementation](https://github.com/gardencmp/jazz/blob/f1dff3e3fda63024bc91acfb11ee7ed36ba6d628/packages/cojson/src/PriorityBasedMessageQueue.ts) I've used a Weighed Round Robin (WRR), the same alg used by Nginx to do load balancing.

While it work great with 3 priority levels (1, 2, 3) I've found that it doesn't work well with an infinite set of priority ranges and the user customization (the priorities should be defined berforehand and the weight system can easily become unbalanced)

I'm also starting to see that in order to fit our requirements the implementation is becoming quite complex.
I would love to have something simple and easy to understand as priority system, because otherwise our user won't be able to take full advantage of it.

Going forwards I'm evaluating the following options:

## Option 1

We could change the priority ranges to meet the ones specified for H2 and H3 

https://www.rfc-editor.org/rfc/rfc9218.html#name-urgency

By having a defined set of priorities finding the right algorithm could become easier and we could reuse WRR for this.

## Option 2

We could totally change approach and aim for a "fair distribution" of the peer resources, so without relying on defined priorities, using an algorithm like this one --> https://rtcl.eecs.umich.edu/rtclweb/assets/publications/2001/feng2001fair.pdf 

This would remove the need of labeling the CoValues with priorities.

## Option 3

We could also make it very simple by just processing the messages by priority.
The risk is that when the queue is full of high priority values the low priority ones never get processed.

There are plenty of ready to use libraries for this use case and it is probably the quickest to implement.

Can be very low overhead if we go for a limited set of priorities (like the HTTP priority levels) 

Example: [Fast Priority Queue](https://www.npmjs.com/package/fastpriorityqueue)

-------

I personally would lean towards the option 3 with a limited set of priorities.

We are probably going to modify the algorithm in the future anyway and if we go with the simplest path it's going to be easier to switch or expand it.

**Comment by aeplay** [comment]
Let's go with Option 3 + the priority schema from Option 1
