### ISSUE TITLE
jazz.tools demo is broken

### ISSUE THREAD

**Issue by staeter** [garden-co/classic-jazz#727]
I copied the link to chat with myself between different browsers and I got stuck on infinite loading. Doesn't look good for new users.

**Comment by aeplay** [comment]
Thanks for letting us know! This is resolved now. It was caused due to one app using Jazz suddenly seeing a lot more users and our infrastructure experiencing some temporary growing pains. Apologies!

More details: https://discord.com/channels/1139617727565271160/1139617728580305018/1305495735579574364
